name: Release [Dev]

on: 
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Module
        run: npm i
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Module
        run: npm i
      - name: "Test"
        run: npm run test:cov

  semantic: 
    runs-on: ubuntu-latest
    needs: 
      - "lint"
      - "test"
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm i
      - run: npm run build
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
  docker:
    runs-on: ubuntu-latest
    needs: 
      - "lint"
      - "test"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        run: |
          echo $CR_PAT | docker login ghcr.io -u KUTask --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/kutask/backend-dev:latest
  